# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

- name: Configure photoview user
  user:
    name: photoview
    state: present
  register: photoview_user
  become: yes

- name: Prepare Photoview base directories
  file:
    path: '{{ item.path }}'
    state: directory
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
    mode: '{{ item.mode }}'
  loop:
    - path: '{{ photoview_root_path }}'
      owner: root
      group: root
      mode: '0755'
    - path: '{{ photoview_root_path }}/{{ photoview_name }}'
      owner: root
      group: root
      mode: '0755'
    - path: '{{ photoview_root_path }}/{{ photoview_name }}/cache'
      owner: photoview
      group: photoview
      mode: '0700'
    - path: '{{ photoview_root_path }}/{{ photoview_name }}/photos'
      owner: root
      group: root
      mode: '0755'
  become: yes

- name: Configure docker compose for Photoview
  template:
    src: '{{ item.name }}.j2'
    dest: '{{ photoview_root_path }}/{{ photoview_name }}/{{ item.name }}'
    owner: root
    group: root
    mode: '{{ item.mode }}'
  loop:
    - name: docker-compose.yml
      mode: '0644'
    - name: ENV
      mode: '0600'
  become: yes

- name: Install Photoview service file
  template:
    src: photoview@.service.j2
    dest: '/etc/systemd/system/photoview@.service'
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Reload systemd units
  systemd:
    daemon_reload: yes
  when: 'not ansible_check_mode'
  become: yes

- name: Restart Photoview services
  service:
    name: 'photoview@{{ photoview_name }}'
    state: restarted
    enabled: yes
  when: 'not ansible_check_mode'
  become: yes
