# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

- name: Install packages
  apt:
    update_cache: yes
    pkg:
      - postgresql
      - postgresql-client
      - python3-psycopg2
      - acl
    state: latest
  become: yes

- name: Start PostgreSQL service
  service:
    name: postgresql
    state: started
    enabled: yes
  become: yes

- name: Create database-specific users
  community.postgresql.postgresql_user:
    name: '{{ item.user }}'
    password: '{{ item.password }}'
    state: present
  loop: '{{ postgresql_databases }}'
  become: yes
  become_user: postgres

- name: Create databases
  community.postgresql.postgresql_db:
    name: '{{ item.database }}'
    state: present
  loop: '{{ postgresql_databases }}'
  become: yes
  become_user: postgres

- name: Grant database access to specific users
  community.postgresql.postgresql_privs:
    type: database
    database: '{{ item.database }}'
    roles: '{{ item.user }}'
    grant_option: no
    privs: all
  loop: '{{ postgresql_databases }}'
  become: yes
  become_user: postgres
