# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

- name: Install packages
  apt:
    update_cache: yes
    pkg:
      - postgresql
      - postgresql-client
      - python3-psycopg2
      - acl
    state: latest
  become: yes

- name: Configure PostgreSQL listen addresses
  lineinfile:
    dest: /etc/postgresql/13/main/postgresql.conf
    regexp: '^listen_addresses'
    line: "listen_addresses = '127.0.0.1, 172.17.0.1'"
    state: present
  become: yes

- name: Allow connection from Docker containers
  lineinfile:
    dest: /etc/postgresql/13/main/pg_hba.conf
    regexp: '192.168.0.0'
    line: 'host    all             all             192.168.0.0/16          md5'
    state: present
  become: yes

- name: Make sure PostgreSQL starts after Docker
  lineinfile:
    dest: /lib/systemd/system/postgresql.service
    line: 'After=docker.service'
    insertafter: '^Description'
    firstmatch: yes
    state: present
  become: yes

- name: Start PostgreSQL service
  service:
    name: postgresql
    state: started
    enabled: yes
  become: yes

- name: Create database-specific users
  community.postgresql.postgresql_user:
    name: '{{ item.user }}'
    password: '{{ item.password }}'
    state: present
  loop: '{{ postgresql_databases }}'
  become: yes
  become_user: postgres

- name: Create databases
  community.postgresql.postgresql_db:
    name: '{{ item.database }}'
    state: present
  loop: '{{ postgresql_databases }}'
  become: yes
  become_user: postgres

- name: Grant database access to specific users
  community.postgresql.postgresql_privs:
    type: database
    database: '{{ item.database }}'
    roles: '{{ item.user }}'
    grant_option: no
    privs: all
  loop: '{{ postgresql_databases }}'
  become: yes
  become_user: postgres

- name: Create backup directories
  file:
    path: '{{ item.path }}'
    state: directory
    owner: root
    group: postgres
    mode: '{{ item.mode }}'
  loop:
    - path: '{{ postgresql_backup_path }}'
      mode: '0755'
    - path: '{{ postgresql_backup_path }}/backups'
      mode: '0770'
  become: yes

- name: Create backup script
  template:
    src: backup.sh.j2
    dest: '{{ postgresql_backup_path }}/backup.sh'
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Install scheduled backup systemd units
  template:
    src: '{{ item }}.j2'
    dest: '/etc/systemd/system/{{ item }}'
    owner: root
    group: root
    mode: '0644'
  loop:
    - postgresql_backup.service
    - postgresql_backup.timer
  become: yes

- name: Reload systemd units
  systemd:
    daemon_reload: yes
  when: 'not ansible_check_mode'
  become: yes

- name: Enabled scheduled backups
  service:
    name: postgresql_backup.timer
    state: started
    enabled: yes
  become: yes

