# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

nginx_domains:
  - name: git.f2rsmpsy.org
    ssl_certbot_email: niels.martignene@protonmail.com
    config: |
      location / {
          proxy_http_version 1.1;
          proxy_buffering on;
          proxy_read_timeout 180;
          send_timeout 180;

          # Protect from basic scrappers, but allow blackbox and git clone!
          if ($http_user_agent ~* "|blackbox|git/|git-lfs/") {
              set $bypass_cookie 1;
          }
          if ($cookie_open_the_door = "1") {
              set $bypass_cookie 1;
          }
          if ($bypass_cookie != 1) {
              add_header Content-Type text/html always;
              return 418 '<script>document.cookie = "open_the_door=1; Path=/;"; window.location.reload();</script>';
          }

          proxy_request_buffering off;
          client_max_body_size 2G;

          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_pass http://127.0.0.1:3000/;
      }

prometheus_exporters:
  - node_exporter
  - nginx_exporter
  - systemd_exporter
