# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

nginx_domains:
  - name: '{{ ansible_host }}'
    config: |
      ssl_client_certificate /opt/nginx/ssl/internal/ca.crt;
      ssl_verify_client on;
      ssl_verify_depth 2;

      {% for exporter in prometheus_exporters %}

      location /metrics/{{ exporter }} {
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_pass http://127.0.0.1:{{ prometheus_packages[exporter].port }}/metrics;
      }
      {% endfor %}

  - name: git.f2rsmpsy.org
    ssl_certbot_email: niels.martignene@protonmail.com
    config: |
      location / {
          proxy_http_version 1.1;
          proxy_buffering on;
          proxy_read_timeout 180;
          send_timeout 180;

          # Protect from basic scrappers, but allow blackbox and git clone!
          if ($http_user_agent ~* "blackbox|git/|git-lfs/") {
              set $bypass_cookie 1;
          }
          if ($cookie_open_the_door = "1") {
              set $bypass_cookie 1;
          }
          if ($bypass_cookie != 1) {
              add_header Content-Type text/html always;
              return 418 '<script>document.cookie = "open_the_door=1; Path=/;"; window.location.reload();</script>';
          }

          proxy_request_buffering off;
          client_max_body_size 2G;

          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_pass http://127.0.0.1:3000/;
      }

  - name: chat.f2rsmpsy.org
    ssl_certbot_email: niels.martignene@protonmail.com
    config: |
      location ~ /api/v[0-9]+/(users/)?websocket$ {
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          client_max_body_size 64M;
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Frame-Options SAMEORIGIN;
          proxy_buffers 256 16k;
          proxy_buffer_size 16k;
          client_body_timeout 60;
          send_timeout 300;
          lingering_timeout 5;
          proxy_connect_timeout 90;
          proxy_send_timeout 300;
          proxy_read_timeout 90s;
          proxy_http_version 1.1;
          proxy_pass http://127.0.0.1:8065;
      }

      location / {
          client_max_body_size 64M;
          proxy_set_header Connection "";
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Frame-Options SAMEORIGIN;
          proxy_buffers 256 16k;
          proxy_buffer_size 16k;
          proxy_read_timeout 600s;
          proxy_http_version 1.1;
          proxy_pass http://127.0.0.1:8065;
      }

  - name: cpad.f2rsmpsy.org
    ssl_certbot_email: niels.martignene@protonmail.com
    config: |
      location / {
          proxy_http_version    1.1;

          proxy_set_header      X-Real-IP $remote_addr;
          proxy_set_header      Host $host;
          proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
          client_max_body_size  150m;

          proxy_set_header      Upgrade $http_upgrade;
          proxy_set_header      Connection upgrade;

          proxy_pass            http://localhost:4242;
      }

  - name: cpadsb.f2rsmpsy.org
    ssl_certbot_email: niels.martignene@protonmail.com
    config: |
      location / {
          proxy_http_version    1.1;

          proxy_set_header      X-Real-IP $remote_addr;
          proxy_set_header      Host $host;
          proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
          client_max_body_size  150m;

          proxy_set_header      Upgrade $http_upgrade;
          proxy_set_header      Connection upgrade;

          proxy_pass            http://localhost:4242;
      }

  - name: forum.f2rsmpsy.org
    ssl_certbot_email: niels.martignene@protonmail.com
    config: |
      location / {
          # limit_req zone=default burst=100 nodelay;

          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-Proto https;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Real-IP $remote_addr;

          proxy_pass http://unix:/opt/discourse/f2rsmpsy/shared/nginx.http.sock:;
      }

  - name: vault.f2rsmpsy.org
    ssl_certbot_email: niels.martignene@protonmail.com
    config: |
      location / {
          # limit_req zone=default burst=100 nodelay;

          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-Proto https;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Real-IP $remote_addr;

          proxy_pass http://127.0.0.1:8285;
      }

  - name: drop.f2rsmpsy.org
    ssl_certbot_email: niels.martignene@protonmail.com
    config: |
      location / {
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $connection_upgrade;

          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Remote-Port $remote_port;

          proxy_redirect off;
          proxy_pass http://127.0.0.1:12000;
      }

  - name: i18n.koromix.dev
    ssl_certbot_email: niels.martignene@protonmail.com
    config: |
      location / {
          # limit_req zone=default burst=100 nodelay;

          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-Proto https;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Real-IP $remote_addr;

          proxy_pass http://127.0.0.1:8364;
      }

prometheus_exporters:
  - node_exporter
  - nginx_exporter
  - systemd_exporter
