# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

- name: Load Prometheus information
  include_vars:
    file: ../prometheus/vars/main.yml
  when: 'nginx_front is not defined'

- name: Gather domain names
  block:
    - name: Gather domain names 1/3
      set_fact:
        nginx_certificates_direct: '{{ nginx_domains | default([]) }}'
    - name: Gather domain names 2/3
      set_fact:
        nginx_certificates_front: '{{ hostvars.values() | selectattr("nginx_front", "defined") | selectattr("nginx_front", "equalto", inventory_hostname) | map(attribute = "nginx_domains", default = []) | list | flatten }}'
    - name: Gather domain names 3/3
      set_fact:
        nginx_certificates: '{{ nginx_certificates_direct | union(nginx_certificates_front) }}'
  when: 'nginx_front is not defined'
  become: no

- name: Bootstrap missing Certbot certificates
  shell:
    cmd: |
      ln -sf "/opt/nginx/ssl/internal/{{ inventory_hostname }}.key" "/opt/nginx/ssl/letsencrypt/{{ item.name }}.key"
      ln -sf "/opt/nginx/ssl/internal/{{ inventory_hostname }}.crt" "/opt/nginx/ssl/letsencrypt/{{ item.name }}.crt"
    creates: '/opt/nginx/ssl/letsencrypt/{{ item.name }}.key'
  loop: '{{ nginx_certificates }}'
  when: 'nginx_front is not defined'
  become: yes

- name: Reload NGINX (for certbot)
  service:
    name: nginx
    state: reloaded
  when: 'not ansible_check_mode'
  become: yes

- name: Prepare webroot directories for certbot
  file:
    path: '/opt/nginx/ssl/webroot/{{ item.name }}'
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop: '{{ nginx_certificates }}'
  when: 'nginx_front is not defined and not force_self_ssl and item.ssl_certbot_email is defined'
  become: yes

- name: Generate Certbot certificates
  shell:
    cmd: |
      rm -rf /etc/letsencrypt/live/{{ item.name }} /etc/letsencrypt/renewal/{{ item.name }}.conf /etc/letsencrypt/archive/{{ item.name }}
      certbot certonly --cert-name {{ item.name }} --webroot --preferred-challenges http -w /opt/nginx/ssl/webroot/{{ item.name }} -d {{ item.name }} -m {{ item.ssl_certbot_email }} --agree-tos --noninteractive {{ item.ssl_certbot_options | default(ssl_certbot_options) }}
    creates: '/etc/letsencrypt/live/{{ item.name }}/chain.pem'
  register: certbot_gen
  retries: 3
  delay: 6
  until: 'certbot_gen is not failed'
  loop: '{{ nginx_certificates }}'
  when: 'nginx_front is not defined and not force_self_ssl and item.ssl_certbot_email is defined'
  become: yes

- name: Create Certbot key symbolic links
  file:
    state: link
    path: '/opt/nginx/ssl/letsencrypt/{{ item.name }}.key'
    src: '/etc/letsencrypt/live/{{ item.name }}/privkey.pem'
  loop: '{{ nginx_certificates }}'
  when: 'nginx_front is not defined and not force_self_ssl and item.ssl_certbot_email is defined'
  become: yes

- name: Create Certbot certificate symbolic links
  file:
    state: link
    path: '/opt/nginx/ssl/letsencrypt/{{ item.name }}.crt'
    src: '/etc/letsencrypt/live/{{ item.name }}/fullchain.pem'
  loop: '{{ nginx_certificates }}'
  when: 'nginx_front is not defined and not force_self_ssl and item.ssl_certbot_email is defined'
  become: yes

- name: Make sure Certbot post-renewal directory exists
  file:
    state: directory
    path: /etc/letsencrypt/renewal-hooks/post
    owner: root
    group: root
    mode: '0755'
  when: 'nginx_front is not defined and not force_self_ssl'
  become: yes

- name: Install post-renewal script
  template:
    src: certbot_reload.sh.j2
    dest: /etc/letsencrypt/renewal-hooks/post/reload.sh
    owner: root
    group: root
    mode: '0755'
  when: 'nginx_front is not defined and not force_self_ssl'
  become: yes

- name: List old certbot renewals
  find:
    paths:
      - /etc/letsencrypt/renewal
      - /etc/letsencrypt/archive
      - /etc/letsencrypt/live
      - /opt/nginx/ssl/letsencrypt
    file_type: any
    recurse: no
    exclude: |
      {{ nginx_certificates | map(attribute = "name") | list |
         union(nginx_certificates | map(attribute = "name") | map("regex_replace", "^(.*)$", "\1.conf") | list) |
         union(nginx_certificates | map(attribute = "name") | map("regex_replace", "^(.*)$", "\1.key") | list) |
         union(nginx_certificates | map(attribute = "name") | map("regex_replace", "^(.*)$", "\1.crt") | list) |
         union(["README"]) }}
  register: certbot_old
  when: 'nginx_front is not defined and not force_self_ssl'
  become: yes

- name: Clean up old certbot renewals
  file:
    path: '{{ item.path }}'
    state: absent
  loop: '{{ certbot_old.files }}'
  when: 'nginx_front is not defined and not force_self_ssl'
  become: yes

- name: Remove custom certbot systemd units
  file:
    path: '/etc/systemd/system/{{ item }}'
    state: absent
  loop:
    - certbot.service
    - certbot.timer
  when: 'nginx_front is not defined'
  become: yes

- name: Reload systemd units
  systemd:
    daemon_reload: yes
  when: 'not ansible_check_mode'
  become: yes

- name: Enable certbot renewal unit
  service:
    name: certbot.timer
    state: started
    enabled: yes
  when: 'nginx_front is not defined and not force_self_ssl'
  become: yes
