# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

nextcloud_url: https://download.nextcloud.com/server/releases/nextcloud-28.0.4.tar.bz2
nextcloud_checksum: 'sha256:9bfecee1e12fba48c49e9a71caa81c4ba10b2884787fab75d64ccfd122a13019'

nextcloud_root_path: /opt/nextcloud

nextcloud_default_user: admin
nextcloud_default_password: admin

# nextcloud_name:
# nextcloud_domain:
# nextcloud_database:

# nextcloud_smtp:

nextcloud_max_children: 12
nextcloud_memory_limit: 512M

# onlyoffice_port:
# onlyoffice_jwt_secret:
