# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

nextcloud_url: https://download.nextcloud.com/server/releases/nextcloud-29.0.5.tar.bz2
nextcloud_checksum: 'sha256:c7fe9c61e5ec30a5e599e8f152a1825df684d30e899db0caa8868c8d67b53a2c'

nextcloud_root_path: /opt/nextcloud

nextcloud_default_user: admin
nextcloud_default_password: admin

# nextcloud_name:
# nextcloud_domain:
# nextcloud_database:

# nextcloud_smtp:

nextcloud_fpm_pm: ondemand
nextcloud_fpm_config:
  max_children: 12
  process_idle_timeout: 60s
nextcloud_memory_limit: 512M

onlyoffice_image: onlyoffice/documentserver:8.1.3.1

# onlyoffice_port:
# onlyoffice_jwt_secret:
