# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

rokkerd_repo: https://git.interactions-team.fr/Koromix/rygel.git
rokkerd_commit: master

rokkerd_root_path: /opt/rokkerd # Installation directory
rokkerd_run_user: rokkerd # POSIX user that will run THOP services
rokkerd_run_group: rokkerd # POSIX group that will run THOP services

rokkerd_sandbox: yes

# rokkerd_name:
# rokkerd_title:
# rokkerd_url:

# rokkerd_smtp:
#   url:
#   username:
#   password:
#   from:
