# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

limesurvey_url: https://download.limesurvey.org/latest-master/limesurvey7.0.15+260910.zip
limesurvey_checksum: 'sha256:7db65c36d22dac64b4b3e69b46741dcd193a90cfd236fafdb60f748d04b9e72b'

limesurvey_root_path: /opt/limesurvey

# limesurvey_name: blog
# limesurvey_title:
# limesurvey_home:
# limesurvey_admin_password:
# limesurvey_admin_mail:
# limesurvey_database:
# limesurvey_smtp:

limesurvey_patches:
  - fix-classic-subquestion-removal.patch
