# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

- name: Install packages
  package:
    update_cache: yes
    pkg:
      - build-essential
      - redis-server
      - imagemagick
    state: latest
  become: yes

- name: Configure overleaf user
  user:
    name: overleaf
    state: present
  register: overleaf_user
  become: yes

- name: Bind Redis to Docker address
  lineinfile:
    dest: /etc/redis/redis.conf
    line: 'bind 172.17.0.1 -::1'
    insertafter: '^bind '
    state: present
  become: yes

- name: Disable Redis protected mode
  lineinfile:
    dest: /etc/redis/redis.conf
    regexp: '^protected-mode'
    line: 'protected-mode no'
    state: present
  become: yes

- name: Prepare Overleaf base directories
  file:
    path: '{{ item.path }}'
    state: directory
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
    mode: '{{ item.mode }}'
  loop:
    - path: '{{ overleaf_root_path }}'
      owner: root
      group: root
      mode: '0755'
    - path: '{{ overleaf_root_path }}/repo'
      owner: root
      group: root
      mode: '0755'
    - path: '{{ overleaf_root_path }}/{{ overleaf_name }}'
      owner: root
      group: root
      mode: '0755'
    - path: '{{ overleaf_root_path }}/{{ overleaf_name }}/app'
      owner: root
      group: root
      mode: '0755'
    - path: '{{ overleaf_root_path }}/{{ overleaf_name }}/data'
      owner: overleaf
      group: overleaf
      mode: '0700'
  become: yes

- name: Fetch Overleaf repository
  git:
    repo: '{{ overleaf_repo }}'
    version: '{{ overleaf_commit }}'
    dest: '{{ overleaf_root_path }}/repo'
    force: yes
  become: yes

- name: Build base
  command:
    cmd: 'make build-base'
    chdir: '{{ overleaf_root_path }}/repo/server-ce'
  become: yes

- name: Build community
  command:
    cmd: 'make build-community'
    chdir: '{{ overleaf_root_path }}/repo/server-ce'
  become: yes

- name: Configure docker compose for Overleaf
  template:
    src: '{{ item.name }}.j2'
    dest: '{{ overleaf_root_path }}/{{ overleaf_name }}/app/{{ item.name }}'
    owner: root
    group: root
    mode: '{{ item.mode }}'
  loop:
    - name: docker-compose.yml
      mode: '0644'
    - name: ENV
      mode: '0600'
  become: yes

- name: Install Overleaf service file
  template:
    src: overleaf@.service.j2
    dest: '/etc/systemd/system/overleaf@.service'
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Reload systemd units
  systemd:
    daemon_reload: yes
  when: 'not ansible_check_mode'
  become: yes

- name: Restart Redis service
  service:
    name: redis
    state: restarted
    enabled: yes
  when: 'not ansible_check_mode'
  become: yes

- name: Restart Overleaf services
  service:
    name: 'overleaf@{{ overleaf_name }}'
    state: restarted
    enabled: yes
  when: 'not ansible_check_mode'
  become: yes
