# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTIcdCULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

mattermost_url: https://releases.mattermost.com/10.8.1/mattermost-10.8.1-linux-amd64.tar.gz
mattermost_checksum: 'sha256:f132f0c815f4db9ffbd39207885c5a601117922eb9a08f5a287fec65c40df426'

mattermost_root_path: /opt/mattermost

mattermost_port: 8065

# mattermost_name:
# mattermost_root:
# mattermost_database:
# mattermost_smtp:
