# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTIcdCULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

mattermost_url: https://releases.mattermost.com/11.7.3/mattermost-11.7.3-linux-amd64.tar.gz
mattermost_checksum: 'sha256:b3e460c8e79d00eeb6c667a2e830bd9f3c123530c7a73e2caf4dd7c86ce2cc0a'

mattermost_root_path: /opt/mattermost

mattermost_port: 8065
mattermost_locale: en

# mattermost_name:
# mattermost_root:
# mattermost_database:
# mattermost_smtp:
# mattermost_support:
