# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTIcdCULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

mattermost_url: https://releases.mattermost.com/11.7.2/mattermost-11.7.2-linux-amd64.tar.gz
mattermost_checksum: 'sha256:8882f3a26f0e324c5f4dc253a3388b4772d907e345c99286f35fd0aa5be9c125'

mattermost_root_path: /opt/mattermost

mattermost_port: 8065
mattermost_locale: en

# mattermost_name:
# mattermost_root:
# mattermost_database:
# mattermost_smtp:
# mattermost_support:
