# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

rekkorddrop_repo: https://git.interactions-team.fr/Koromix/rygel.git
rekkorddrop_commit: master

rekkorddrop_root_path: /opt/rekkorddrop # Installation directory
rekkorddrop_run_user: rekkorddrop # POSIX user that will run THOP services
rekkorddrop_run_group: rekkorddrop # POSIX group that will run THOP services

rekkorddrop_sandbox: yes

# rekkorddrop_name:
# rekkorddrop_title:
# rekkorddrop_url:

rekkorddrop_quota: 10G

# rekkorddrop_smtp:
#   url:
#   username:
#   password:
#   from:

# rekkorddrop_s3:
#   location:
#   access_key_id:
#   secret_access_key:
