# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

- name: Install packages
  apt:
    update_cache: no
    pkg:
      - git
    state: latest
  become: yes

- name: Prepare Discourse base directories
  file:
    path: '{{ item.path }}'
    state: directory
    owner: root
    group: root
    mode: '{{ item.mode }}'
  loop:
    - path: '{{ discourse_root_path }}'
      mode: '0755'
    - path: '{{ discourse_root_path }}/{{ discourse_name }}'
      mode: '0755'
  become: yes

- name: Clone Discourse docker
  git:
    repo: '{{ discourse_repo }}'
    version: '{{ discourse_commit }}'
    dest: '{{ discourse_root_path }}/{{ discourse_name }}'
    force: yes
  become: yes

- name: Configure Discourse container
  template:
    src: app.yml.j2
    dest: '{{ discourse_root_path }}/{{ discourse_name }}/containers/app.yml'
    owner: root
    group: root
    mode: '0600'
  become: yes

- name: Build Discourse app
  command:
    cmd: '{{ discourse_root_path }}/{{ discourse_name }}/launcher rebuild app'
    chdir: '{{ discourse_root_path }}/{{ discourse_name }}'
  when: 'not ansible_check_mode'
  become: yes
