# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

gitea_url: https://dl.gitea.com/gitea/1.21.1/gitea-1.21.1-linux-amd64
gitea_checksum: 'sha256:586b1b0df6940e847600625850ee7d766f103dc3341c1b4abfc269db57c5d826'

gitea_root_path: /opt/gitea

gitea_port: 3000
gitea_config:

# gitea_domain:
# gitea_smtp:
