# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

alicare_repo: https://git.interactions-team.fr/INTERACTIONS/calypso.git
alicare_commit: main

alicare_root_path: /opt/alicare # Installation directory
alicare_run_user: alicare # POSIX user that will run service
alicare_run_group: alicare # POSIX group that will run service

alicare_sandbox: yes

# alicare_name:
# alicare_title:
# alicare_url:

# alicare_smtp:
#   url:
#   username:
#   password:
#   from:

alicare_auth:
  internal: yes
  register: yes
