# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

- name: Install packages
  apt:
    update_cache: yes
    pkg:
      - git
    state: latest
  become: yes

- name: Configure forgejo user
  user:
    name: forgejo
    state: present
  become: yes

- name: Prepare Forgejo base directory
  file:
    path: '{{ forgejo_root_path }}'
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Prepare Forgejo data directories
  file:
    path: '{{ item }}'
    state: directory
    owner: forgejo
    group: forgejo
    mode: '0750'
  loop:
    - '{{ forgejo_root_path }}/custom'
    - '{{ forgejo_root_path }}/etc'
    - '{{ forgejo_root_path }}/data'
    - '{{ forgejo_root_path }}/log'
  become: yes

- name: Fetch Forgejo binary
  get_url:
    url: '{{ forgejo_url }}'
    dest: '{{ forgejo_root_path }}/forgejo'
    checksum: '{{ forgejo_checksum }}'
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Configure Forgejo
  template:
    src: app.ini.j2
    dest: '{{ forgejo_root_path }}/etc/app.ini'
    owner: forgejo
    group: forgejo
    mode: '0644'
  become: yes

- name: Create Forgejo keys
  shell:
    cmd: '{{ forgejo_root_path }}/forgejo generate secret {{ item | upper }} > etc/{{ item }}'
    chdir: '{{ forgejo_root_path }}'
    creates: '{{ forgejo_root_path }}/etc/{{ item }}'
  loop:
    - secret_key
    - internal_token
  become: yes

- name: Securize Forgejo keys
  file:
    path: '{{ forgejo_root_path }}/etc/{{ item }}'
    state: file
    owner: forgejo
    group: forgejo
    mode: '0600'
  loop:
    - secret_key
    - internal_token
  become: yes

- name: Install Forgejo service file
  template:
    src: forgejo.service.j2
    dest: '/etc/systemd/system/forgejo.service'
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Reload systemd units
  systemd:
    daemon_reload: yes
  when: 'not ansible_check_mode'
  become: yes

- name: Restart Forgejo service
  service:
    name: forgejo
    enabled: yes
    state: restarted
  when: 'not ansible_check_mode'
  become: yes
