# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

pri_cloud_ip = '192.168.59.4'
pri_tools_ip = '192.168.59.6'
pri_cpad_ip = '192.168.59.7'
pri_forum_ip = '192.168.59.8'
pub_cloud_ip = '192.168.59.10'
pub_leaks_ip = '192.168.59.5'
pub_web_ip = '192.168.59.3'
vpn_ip = '192.168.59.10'

Vagrant.configure('2') do |config|
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true

    config.vm.define 'pri_cloud' do |m|
        m.vm.box = 'generic/debian11'
        m.vm.hostname = 'cloud.intra.mla.local'
        m.vm.network 'private_network', ip: pri_cloud_ip

        m.vm.provider 'virtualbox' do |v|
            v.name = 'mla_pri_cloud'
            v.memory = 2048
            v.cpus = 1
            v.linked_clone = true
            v.gui = false
        end
    end

    config.vm.define 'pri_cpad' do |m|
        m.vm.box = 'generic/debian11'
        m.vm.hostname = 'cpad.intra.mla.local'
        m.vm.network 'private_network', ip: pri_cpad_ip

        m.hostmanager.aliases = ['cpadsb.intra.mla.local']

        m.vm.provider 'virtualbox' do |v|
            v.name = 'mla_pri_cpad'
            v.memory = 1024
            v.cpus = 1
            v.linked_clone = true
            v.gui = false
        end
    end

    config.vm.define 'pri_tools' do |m|
        m.vm.box = 'generic/debian11'
        m.vm.hostname = 'tools.intra.mla.local'
        m.vm.network 'private_network', ip: pri_tools_ip

        m.hostmanager.aliases = ['vault.intra.mla.local', 'wekan.intra.mla.local']

        m.vm.provider 'virtualbox' do |v|
            v.name = 'mla_pri_tools'
            v.memory = 2048
            v.cpus = 1
            v.linked_clone = true
            v.gui = false
        end
    end

    config.vm.define 'pri_forum' do |m|
        m.vm.box = 'generic/debian11'
        m.vm.hostname = 'forum.intra.mla.local'
        m.vm.network 'private_network', ip: pri_forum_ip

        m.vm.provider 'virtualbox' do |v|
            v.name = 'mla_pri_forum'
            v.memory = 2048
            v.cpus = 2
            v.linked_clone = true
            v.gui = false
        end
    end

    config.vm.define 'pub_cloud' do |m|
        m.vm.box = 'generic/debian11'
        m.vm.hostname = 'cloud.mla.local'
        m.vm.network 'private_network', ip: pub_cloud_ip

        m.vm.provider 'virtualbox' do |v|
            v.name = 'mla_pub_cloud'
            v.memory = 2048
            v.cpus = 1
            v.linked_clone = true
            v.gui = false
        end
    end

    config.vm.define 'pub_leaks' do |m|
        m.vm.box = 'generic/debian11'
        m.vm.hostname = 'leaks.mla.local'
        m.vm.network 'private_network', ip: pub_leaks_ip

        m.vm.provider 'virtualbox' do |v|
            v.name = 'mla_pub_leaks'
            v.memory = 2048
            v.cpus = 1
            v.linked_clone = true
            v.gui = false
        end
    end

    config.vm.define 'vpn' do |m|
        m.vm.box = 'generic/debian11'
        m.vm.hostname = 'vpn.mla.local'
        m.vm.network 'private_network', ip: vpn_ip

        m.vm.provider 'virtualbox' do |v|
            v.name = 'mla_vpn'
            v.memory = 2048
            v.cpus = 1
            v.linked_clone = true
            v.gui = false
        end
    end

    config.vm.define 'pub_web' do |m|
        m.vm.box = 'generic/debian11'
        m.vm.hostname = 'mla.local'
        m.vm.network 'private_network', ip: pub_web_ip

        m.vm.provider 'virtualbox' do |v|
            v.name = 'mla_pub_web'
            v.memory = 2048
            v.cpus = 1
            v.linked_clone = true
            v.gui = false
        end

        m.vm.provision 'ansible' do |ansible|
            ansible.playbook = '../mla.yml'
            ansible.limit = 'all'
            ansible.inventory_path = '../inventories/vagrant/hosts.yml'
            ansible.extra_vars = { ansible_python_interpreter: '/usr/bin/python3' }
            ansible.vault_password_file = '../ansible_mla.vault'
            # ansible.raw_arguments = ['--check']
        end
    end
end
