# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

monitor_ip = '192.168.59.2'
public_ip = '192.168.59.3'
vault_ip = '192.168.59.4'
leaks_ip = '192.168.59.5'

Vagrant.configure('2') do |config|
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true

    config.vm.define 'monitor' do |m|
        m.vm.box = 'generic/debian11'
        m.vm.hostname = 'monitor.mla.local'
        m.vm.network 'private_network', ip: monitor_ip

        m.vm.provider 'virtualbox' do |v|
            v.name = 'mla_monitor'
            v.memory = 1024
            v.cpus = 1
            v.linked_clone = true
            v.gui = false
        end
    end

    config.vm.define 'public' do |m|
        m.vm.box = 'generic/debian11'
        m.vm.hostname = 'mla.local'
        m.vm.network 'private_network', ip: public_ip

        m.vm.provider 'virtualbox' do |v|
            v.name = 'mla_public'
            v.memory = 2048
            v.cpus = 2
            v.linked_clone = true
            v.gui = false
        end
    end

    config.vm.define 'vault' do |m|
        m.vm.box = 'generic/debian11'
        m.vm.hostname = 'vault.mla.local'
        m.vm.network 'private_network', ip: vault_ip

        m.vm.provider 'virtualbox' do |v|
            v.name = 'mla_vault'
            v.memory = 4096
            v.cpus = 4
            v.linked_clone = true
            v.gui = false
        end

        m.vm.provision 'ansible' do |ansible|
            ansible.playbook = '../mla.yml'
            ansible.limit = 'all'
            ansible.inventory_path = '../inventories/vagrant/hosts.yml'
            ansible.extra_vars = { ansible_python_interpreter: '/usr/bin/python3' }
            # ansible.raw_arguments = ['--check']
        end
    end

    config.vm.define 'leaks' do |m|
        m.vm.box = 'generic/debian11'
        m.vm.hostname = 'leaks.mla.local'
        m.vm.network 'private_network', ip: leaks_ip

        m.vm.provider 'virtualbox' do |v|
            v.name = 'mla_leaks'
            v.memory = 4096
            v.cpus = 4
            v.linked_clone = true
            v.gui = false
        end

        m.vm.provision 'ansible' do |ansible|
            ansible.playbook = '../mla.yml'
            ansible.limit = 'all'
            ansible.inventory_path = '../inventories/vagrant/hosts.yml'
            ansible.extra_vars = { ansible_python_interpreter: '/usr/bin/python3' }
            # ansible.raw_arguments = ['--check']
        end
    end
end
