# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

ansible_host: 172.30.239.2
ansible_port: 22
ansible_user: ansible
ansible_ssh_private_key_file: ~/.ssh/mla/preprod
ansible_python_interpreter: /usr/bin/python3

ssh_bind: '{{ ansible_host }}'

ufw_rules:
  - rule: limit
    port: 22
    proto: tcp
  - rule: allow
    port: 80
    proto: tcp
  - rule: allow
    port: 443
    proto: tcp
  - rule: allow
    port: 53
    proto: udp

dnsmasq_addr: '{{ ansible_host }}'
dnsmasq_domains:
  - monitor.intra.premla.fr

lego_domains:
  - domain: monitor.intra.premla.fr
    command: '--email niels.martignene@protonmail.com --dns gandiv5 --domains monitor.intra.premla.fr'
    environment:
      GANDIV5_API_KEY: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        34356161363436643433316337343265313338303631323437636264303431646366323635316465
        3365376538393239376136663161353232656261613930360a653532343465326336346136373539
        37306264363166383962653536303632623232633038653537376433316634336537336234643238
        3433323733313730330a383937366334633739396639303234353565316666616665303963663032
        30666664323962383634323064383631373539303064303332326464313436613932
