# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTIcdCULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

wekan_url: https://github.com/wekan/wekan/releases/download/v7.51/wekan-7.51-amd64.zip
wekan_checksum: 'sha256:0c2830cd039096cc8b4f09ec0b806bf3c611572807a4587b6aa16c9651d52762'

wekan_root_path: /opt/wekan

# wekan_name:
# wekan_root:
# wekan_database:
