# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTIcdCULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

wekan_url: https://github.com/wekan/wekan/releases/download/v6.86/wekan-6.86-amd64.zip
wekan_checksum: 'sha256:7ba973ebdcea96f8c1df212a6d60e3ecc6febc71f638012c2fe4f8cee2eb38cf'

wekan_root_path: /opt/wekan

# wekan_name:
# wekan_root:
# wekan_database:
