# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTIcdCULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

wekan_url: https://github.com/wekan/wekan/releases/download/v7.34/wekan-7.34-amd64.zip
wekan_checksum: 'sha256:6490e1edb1aae60d1b90e1dd182ab7325aa97397266446ae5543fbac82152ea9'

wekan_root_path: /opt/wekan

# wekan_name:
# wekan_root:
# wekan_database:
