# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

ssh_port: 22
restrict_ssh_access: no

force_self_ssl: no

timezone: Etc/UTC

ufw_enable: yes
ufw_rules:
  - rule: allow
    to: '{{ ansible_host if restrict_ssh_access else "any" }}'
    port: 22
    proto: tcp
  - rule: allow
    port: 80
    proto: tcp
  - rule: allow
    port: 443
    proto: tcp

coredump_days: 7

# Use these variables to set up IPv6 on OVH VPS
# Documentation here: https://docs.ovh.com/fr/vps/configurer-ipv6/
# ovh_ipv6_addr:
# ovh_ipv6_netmask:
# ovh_ipv6_gateway:

coredns_root_path: /opt/coredns
coredns_url: https://github.com/coredns/coredns/releases/download/v1.11.4/coredns_1.11.4_linux_amd64.tgz
coredns_checksum: 'sha256:3dd1b565a6b72e04f7c19dc461ffcc7b8e013d520569aa163312384a5be307e5'

agnos_root_path: /opt/agnos
agnos_url: https://github.com/krtab/agnos/releases/download/v0.1.0/agnos_amd64
agnos_checksum: 'sha256:5542e6263d2f67374c856f0b19721aaff3aaa7de54554b86ccde281bb109fc61'

dns_server: no
# dns_authorities:
