# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

- name: Configure SURY repository key
  apt_key:
    url: 'https://packages.sury.org/php/apt.gpg'
    id: 95BD4743
    state: present
  become: yes

- name: Configure SURY repository
  apt_repository:
    repo: 'deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main'
    state: present
  become: yes

- name: Install packages
  apt:
    update_cache: yes
    pkg:
      - php7.4-cli
      - php7.4-mysql
      - php7.4-curl
      - php7.4-gd
      - php7.4-intl
      - php7.4-xml
      - php7.4-mbstring
      - php7.4-zip
      - php7.4-fpm
      - php7.4-memcache
      - php7.4-apcu
      - bzip2
      - acl
    state: latest
  become: yes

- name: Prepare Nextcloud base directory
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - '{{ nextcloud_root_path }}'
    - '{{ nextcloud_root_path }}/{{ nextcloud_name }}'
    - '{{ nextcloud_root_path }}/{{ nextcloud_name }}/new'
    - '{{ nextcloud_root_path }}/{{ nextcloud_name }}/live'
  become: yes

- name: Fetch Nextcloud archive
  get_url:
    url: '{{ nextcloud_url }}'
    dest: '{{ nextcloud_root_path }}/{{ nextcloud_name }}.tar.bz2'
    checksum: '{{ nextcloud_checksum }}'
  become: yes

- name: Extract Nextcloud archive
  unarchive:
    src: '{{ nextcloud_root_path }}/{{ nextcloud_name }}.tar.bz2'
    dest: '{{ nextcloud_root_path }}/{{ nextcloud_name }}/new'
    remote_src: yes
    owner: www-data
    group: www-data
    mode: 'u=rwX,g=rX,o=rX'
    extra_opts:
      - '--strip-components=1'
  become: yes

- name: Check for existing Nextcloud install
  stat:
    path: '{{ nextcloud_root_path }}/{{ nextcloud_name }}/live/config/config.php'
  register: install_check
  become: yes

- name: Copy Nextcloud install
  synchronize:
    src: '{{ nextcloud_root_path }}/{{ nextcloud_name }}/new/'
    dest: '{{ nextcloud_root_path }}/{{ nextcloud_name }}/live/'
    delete: yes
    recursive: yes
    owner: true
    group: true
  delegate_to: '{{ inventory_hostname }}'
  when: 'not install_check.stat.exists'
  become: yes

- name: Configure Nextcloud install
  shell:
    cmd: |
      /usr/bin/php7.4 occ maintenance:install \
        --database "{{ nextcloud_database.provider }}" --database-host "{{ nextcloud_database.host }}" \
        --database-name "{{ nextcloud_database.name }}" \
        --database-user "{{ nextcloud_database.user }}" --database-pass "{{ nextcloud_database.password }}" \
        --admin-user "{{ nextcloud_default_user }}" --admin-pass "{{ nextcloud_default_password }}"
      rm -f config/CAN_INSTALL
      chmod 555 .
    chdir: '{{ nextcloud_root_path }}/{{ nextcloud_name }}/live'
  when: 'not install_check.stat.exists'
  become: yes
  become_user: www-data

- name: Synchronize new Nextcloud version
  synchronize:
    src: '{{ nextcloud_root_path }}/{{ nextcloud_name }}/new/'
    dest: '{{ nextcloud_root_path }}/{{ nextcloud_name }}/live/'
    delete: yes
    recursive: yes
    owner: true
    group: true
    rsync_opts:
      - "--exclude=config"
      - "--exclude=data"
      - "--exclude=custom_apps"
  delegate_to: '{{ inventory_hostname }}'
  when: 'install_check.stat.exists'
  become: yes

- name: Upgrade Nextcloud
  shell:
    cmd: '/usr/bin/php7.4 --define apc.enable_cli=1 occ upgrade'
    chdir: '{{ nextcloud_root_path }}/{{ nextcloud_name }}/live'
  when: 'install_check.stat.exists'
  become: yes
  become_user: www-data

- name: Set Nextcloud trusted domains
  lineinfile:
    dest: '{{ nextcloud_root_path }}/{{ nextcloud_name }}/live/config/config.php'
    regexp: "^ *0 => "
    line: "    0 => '{{ nextcloud_domain }}'"
    state: present
  become: yes

- name: Configure SMTP include
  lineinfile:
    dest: '{{ nextcloud_root_path }}/{{ nextcloud_name }}/live/config/config.php'
    regexp: "^ *include\\('smtp\\.php'\\);"
    line: "include('smtp.php');"
    state: '{{ "present" if nextcloud_smtp is defined else "absent" }}'
  become: yes

- name: Configure SMTP server
  template:
    src: smtp.php.j2
    dest: '{{ nextcloud_root_path }}/{{ nextcloud_name }}/live/config/smtp.php'
    owner: www-data
    group: www-data
    mode: '0755'
  when: 'nextcloud_smtp is defined'
  become: yes

- name: Configure PHP-FPM pool
  template:
    src: fpm.conf.j2
    dest: /etc/php/7.4/fpm/pool.d/nextcloud.conf
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Restart PHP-FPM service
  service:
    name: php7.4-fpm
    state: restarted
    enabled: yes
  when: 'not ansible_check_mode'
  become: yes

- name: Configure OnlyOffice
  include_tasks: onlyoffice.yml
  when: 'onlyoffice_port is defined'
