# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

redropp_repo: https://git.interactions-team.fr/Koromix/rygel.git
redropp_commit: redropp/0.7.4

redropp_root_path: /opt/redropp # Installation directory
redropp_run_user: redropp # POSIX user that will run services
redropp_run_group: redropp # POSIX group that will run services

redropp_sandbox: yes

# redropp_name:
# redropp_title:
# redropp_url:

redropp_quota: 10G

# redropp_smtp:
#   url:
#   username:
#   password:
#   from:

# redropp_s3:
#   location:
#   access_key_id:
#   secret_access_key:
