# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

- name: Configure Cryptpad user
  user:
    name: cpad
    state: present
  become: yes

- name: Install packages
  apt:
    update_cache: no
    pkg:
      - nodejs
      - npm
      - git
    state: latest
  become: yes

- name: Prepare Cryptpad base directories
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - '{{ cpad_root_path }}'
    - '{{ cpad_root_path }}/{{ cpad_name }}'
    - '{{ cpad_root_path }}/{{ cpad_name }}/app'
  become: yes

- name: Fetch Cryptpad repository
  git:
    repo: '{{ cpad_repo }}'
    version: '{{ cpad_commit }}'
    dest: '{{ cpad_root_path }}/{{ cpad_name }}/app'
    force: yes
  become: yes

- name: Prepare Cryptpad app directories
  file:
    path: '{{ item.path }}'
    state: directory
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
    mode: '0755'
  loop:
    - path: '{{ cpad_root_path }}/{{ cpad_name }}/app/customize'
      owner: root
      group: root
    - path: '{{ cpad_root_path }}/{{ cpad_name }}/data'
      owner: cpad
      group: cpad
    - path: '{{ cpad_root_path }}/{{ cpad_name }}/data/block'
      owner: cpad
      group: cpad
    - path: '{{ cpad_root_path }}/{{ cpad_name }}/app/data'
      owner: cpad
      group: cpad
  become: yes

- name: Run NPM install
  command:
    cmd: 'npm ci --no-audit'
    chdir: '{{ cpad_root_path }}/{{ cpad_name }}/app'
  register: npm_install
  changed_when: '"up to date" not in npm_install.stdout'
  become: yes

- name: Generate random salt
  block:
  - name: Generate random salt 1/4
    stat:
      path: '{{ cpad_root_path }}/{{ cpad_name }}/salt'
    register: salt1
    become: yes
  - name: Generate random salt 2/4
    copy:
      dest: '{{ cpad_root_path }}/{{ cpad_name }}/salt'
      owner: root
      group: root
      mode: '0644'
      content: '{{ lookup("community.general.random_string", length=64, special=False) }}'
    when: 'not salt1.stat.exists'
    become: yes
  - name: Generate random salt 3/4
    slurp:
      src: '{{ cpad_root_path }}/{{ cpad_name }}/salt'
    register: salt2
    become: yes
  - name: Generate random salt 4/4
    set_fact:
      cpad_salt: '{{ salt2.content | b64decode }}'

- name: Configure Cryptpad
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: '{{ item.owner | default("root") }}'
    group: '{{ item.group | default("root") }}'
    mode: '{{ item.mode | default("0644") }}'
  loop:
    - src: config.js.j2
      dest: '{{ cpad_root_path }}/{{ cpad_name }}/app/config/config.js'
      group: cpad
      mode: '0640'
    - src: application_config.js.j2
      dest: '{{ cpad_root_path }}/{{ cpad_name }}/app/customize/application_config.js'
  become: yes

- name: Install components
  command:
    cmd: 'npm run install:components'
    chdir: '{{ cpad_root_path }}/{{ cpad_name }}/app'
  when: 'not ansible_check_mode'
  become: yes

- name: Install Cryptpad service file
  template:
    src: cryptpad@.service.j2
    dest: '/etc/systemd/system/cryptpad@.service'
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Reload systemd units
  systemd:
    daemon_reload: yes
  when: 'not ansible_check_mode'
  become: yes

- name: Restart Cryptpad services
  service:
    name: 'cryptpad@{{ cpad_name }}'
    state: restarted
    enabled: yes
  when: 'not ansible_check_mode'
  become: yes