# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

monitor_ip = '192.168.58.4'
tools1_ip = '192.168.58.5'
tools2_ip = '192.168.58.7'
wordpress_ip = '192.168.58.6'

Vagrant.configure('2') do |config|
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true

    config.vm.define 'monitor' do |m|
        m.vm.box = 'generic/debian11'
        m.vm.hostname = 'pknet-monitor.local'
        m.vm.network 'private_network', ip: monitor_ip

        m.vm.provider 'virtualbox' do |v|
            v.name = 'pknet_monitor'
            v.memory = 2048
            v.cpus = 1
            v.linked_clone = true
            v.gui = false
        end
    end

    config.vm.define 'tools1' do |m|
        m.vm.box = 'generic/debian11'
        m.vm.hostname = 'pknet-tools1.local'
        m.vm.network 'private_network', ip: tools1_ip

        # It's kind of ugly to hardcode this but.. meh. Keep it simple
        m.hostmanager.aliases = ['git.pknet.local', 'thop.pknet.local', 'chat.pknet.local']

        m.vm.provider 'virtualbox' do |v|
            v.name = 'pknet_tools'
            v.memory = 4096
            v.cpus = 2
            v.linked_clone = true
            v.gui = false
        end
    end

    config.vm.define 'tools2' do |m|
        m.vm.box = 'generic/debian11'
        m.vm.hostname = 'pknet-tools2.local'
        m.vm.network 'private_network', ip: tools2_ip

        # It's kind of ugly to hardcode this but.. meh. Keep it simple
        m.hostmanager.aliases = ['forum.pknet.local']

        m.vm.provider 'virtualbox' do |v|
            v.name = 'pknet_tools2'
            v.memory = 2048
            v.cpus = 1
            v.linked_clone = true
            v.gui = false
        end
    end

    config.vm.define 'wordpress' do |m|
        m.vm.box = 'generic/debian11'
        m.vm.hostname = 'pknet-wordpress.local'
        m.vm.network 'private_network', ip: wordpress_ip

        # It's kind of ugly to hardcode this but.. meh. Keep it simple
        m.hostmanager.aliases = ['cn2r.pknet.local']

        m.vm.provider 'virtualbox' do |v|
            v.name = 'pknet_wordpress'
            v.memory = 4096
            v.cpus = 2
            v.linked_clone = true
            v.gui = false
        end

        m.vm.provision 'ansible' do |ansible|
            ansible.playbook = '../../pknet.yml'
            ansible.limit = 'all'
            ansible.inventory_path = '../inventories/vagrant/hosts.yml'
            ansible.extra_vars = { ansible_python_interpreter: '/usr/bin/python3' }
            ansible.vault_password_file = '../../keys/pknet.vault'
            # ansible.raw_arguments = ['--check']
        end
    end
end
