# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

- name: Install packages
  apt:
    update_cache: yes
    pkg:
      - git
      - clang
      - lld
      - gcc
      - g++
      - unzip
    state: latest
  become: yes

- name: Create rokkerd user
  user:
    name: rokkerd
    create_home: no
    home: /nonexistent
    shell: /usr/sbin/nologin
    system: yes
  register: rokkerd_user
  become: yes

- name: Prepare rokkerd installation directories
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - '{{ rokkerd_root_path }}'
    - '{{ rokkerd_root_path }}/{{ rokkerd_name }}'
  become: yes

- name: Prepare rokkerd data directories
  file:
    path: '{{ item }}'
    state: directory
    owner: rokkerd
    group: rokkerd
    mode: '0755'
  loop:
    - '{{ rokkerd_root_path }}/{{ rokkerd_name }}/data'
    - '{{ rokkerd_root_path }}/{{ rokkerd_name }}/tmp'
  become: yes

- name: Prepare rokkerd repository directory
  file:
    path: '{{ rokkerd_root_path }}/repo'
    state: directory
    owner: '{{ ansible_user | default(lookup("env", "USER"), True) }}'
  become: yes

- name: Fetch rokkerd repository
  git:
    repo: '{{ rokkerd_repo }}'
    version: '{{ rokkerd_commit }}'
    dest: '{{ rokkerd_root_path }}/repo'
    force: yes
  become: no

- name: Update configuration files
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: '{{ item.mode }}'
  loop:
    - src: rokkerd.ini.j2
      dest: '{{ rokkerd_root_path }}/{{ rokkerd_name }}/rokkerd.ini'
      mode: '0644'
    - src: rokkerd@.service.j2
      dest: /etc/systemd/system/rokkerd@.service
      mode: '0644'
  register: upload_config
  become: yes

- name: Reload systemd units
  systemd:
    daemon_reload: yes
  when: upload_config.changed
  become: yes

- name: Bootstrap Felix
  shell:
    cmd: '{{ rokkerd_root_path }}/repo/bootstrap.sh'
    chdir: '{{ rokkerd_root_path }}/repo'
  when: 'not ansible_check_mode'
  become: no

- name: Build rokkerd
  command:
    cmd: '{{ rokkerd_root_path }}/repo/felix -pParanoid --host=:clang:lld rokkerd'
    chdir: '{{ rokkerd_root_path }}/repo'
  register: build_rokkerd
  changed_when: 'build_rokkerd.stderr_lines[-1] != "Nothing to do!" and build_rokkerd.stderr_lines[-2] != "Nothing to do!"'
  become: no

- name: Install rokkerd
  copy:
    src: '{{ rokkerd_root_path }}/repo/bin/Paranoid/rokkerd'
    remote_src: yes
    dest: '{{ rokkerd_root_path }}/rokkerd'
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Enable rokkerd service
  service:
    name: 'rokkerd@{{ rokkerd_name }}'
    enabled: yes
  become: yes

- name: Restart rokkerd
  service:
    name: 'rokkerd@{{ rokkerd_name }}'
    state: restarted
  when: build_rokkerd.changed
  become: yes
