# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

- name: Update and install Goupile
  command: '{{ goupile_root_path }}/sync/update.sh'
  register: build
  changed_when: 'build.stderr_lines[-1] != "Nothing to do!" and build.stderr_lines[-2] != "Nothing to do!"'
  listen: 'Sync Goupile'
  become: yes

- name: Sync Goupile services
  command: '{{ goupile_root_path }}/sync/sync.py'
  register: sync
  changed_when: 'sync.stderr_lines[-1] != ">>> Nothing has changed" and sync.stderr_lines[-2] != ">>> Nothing has changed"'
  listen: 'Sync Goupile'
  become: yes
