# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

overleaf_repo: https://github.com/overleaf/overleaf.git
overleaf_commit: a74c0abdf547a59055f7fb5c6e6a055511298f72

overleaf_root_path: /opt/overleaf

overleaf_port: 4567

# overleaf_title:
# overleaf_url:
# overleaf_admin_mail:
# overleaf_database:

# overleaf_smtp:
