# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

- name: Cryptpad for F2RSMpsy
  hosts: f2rsm1
  roles:
    - role: ../../../../roles/cryptpad
      vars:
        cpad_name: f2rsmpsy
        cpad_main_domain: 'cpad.f2rsmpsy.org'
        cpad_safe_domain: 'cpadsb.f2rsmpsy.org'
        cpad_admin_mail: 'niels.martignene@protonmail.com'
  tags: [cryptpad]
