# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

- name: goupile.org
  hosts: static
  roles:
    - role: ../../roles/static
      vars:
        static_name: goupile.org/files
    - role: ../../roles/static
      vars:
        static_name: goupile.org/www
        static_repo: https://git.interactions-team.fr/Koromix/rygel.git
        static_build:
          - '{{ static_root_path }}/repo/goupile.org/www/web/goupile.org/build.sh'
        static_path: bin/Web/goupile.org
  tags: [goupile.org, static]

- name: koromix.dev
  hosts: static
  roles:
    - role: ../../roles/static
      vars:
        static_name: koromix.dev/www
        static_repo: https://git.interactions-team.fr/Koromix/rygel.git
        static_build:
          - '{{ static_root_path }}/repo/koromix.dev/www/web/koromix.dev/build.sh'
        static_path: bin/Web/koromix.dev
    - role: ../../roles/static
      vars:
        static_name: koromix.dev/games
        static_repo: https://git.interactions-team.fr/Koromix/games.git
        static_build:
          - '{{ static_root_path }}/repo/koromix.dev/games/src/otocyon/build.js'
          - '{{ static_root_path }}/repo/koromix.dev/games/src/staks/build.js'
          - '{{ static_root_path }}/repo/koromix.dev/games/src/trikub/build.js'
          - '{{ static_root_path }}/repo/koromix.dev/games/src/motris/build.js'
          - '{{ static_root_path }}/repo/koromix.dev/games/src/rubus/build.js'
          - '{{ static_root_path }}/repo/koromix.dev/games/src/scroble/build.js'
          - cmd: 'sh -c "gzip -k static/*.js static/*.css static/*.json"'
            chdir: '{{ static_root_path }}/repo/koromix.dev/games/bin/motris'
          - cmd: 'sh -c "gzip -k static/*.js static/*.css static/*.json"'
            chdir: '{{ static_root_path }}/repo/koromix.dev/games/bin/scroble'
        static_path: bin
    - role: ../../roles/static
      vars:
        static_name: koromix.dev/test
  tags: [koromix.dev, static]

- name: koffi.dev
  hosts: static
  roles:
    - role: ../../roles/static
      vars:
        static_name: koffi.dev/www
        static_repo: https://git.interactions-team.fr/Koromix/rygel.git
        static_build:
          - '{{ static_root_path }}/repo/koffi.dev/www/web/koffi.dev/build.sh'
        static_path: bin/Web/koffi.dev
  tags: [koffi.dev, static]

- name: demheter.fr
  hosts: static
  roles:
    - role: ../../roles/static
      vars:
        static_name: demheter.fr/www
        static_repo: https://git.interactions-team.fr/Koromix/rygel.git
        static_build:
          - '{{ static_root_path }}/repo/demheter.fr/www/web/demheter.fr/build.sh'
        static_path: bin/Web/demheter.fr
  tags: [demheter.fr, static]

- name: cn2r.fr test area
  hosts: static
  roles:
    - role: ../../roles/static
      vars:
        static_name: cn2r.fr/test
  tags: [cn2r.fr, static]

- name: interactions-team.fr test area
  hosts: static
  roles:
    - role: ../../roles/static
      vars:
        static_name: interactions-team.fr/test
  tags: [interactions-team.fr, static]

- name: rekkord.org
  hosts: static
  roles:
    - role: ../../roles/static
      vars:
        static_name: rekkord.org/www
        static_repo: https://git.interactions-team.fr/Koromix/rygel.git
        static_build:
          - '{{ static_root_path }}/repo/rekkord.org/www/web/rekkord.org/build.sh'
        static_path: bin/Web/rekkord.org
  tags: [rekkord.org, static]

- name: redropp.org
  hosts: static
  roles:
    - role: ../../roles/static
      vars:
        static_name: redropp.org/www
        static_repo: https://git.interactions-team.fr/Koromix/rygel.git
        static_build:
          - '{{ static_root_path }}/repo/redropp.org/www/web/redropp.org/build.sh'
        static_path: bin/Web/redropp.org
  tags: [redropp.org, static]

- name: ldv-recherche.fr
  hosts: ludivine
  roles:
    - role: ../../roles/static
      vars:
        static_name: ldv-recherche.fr/www
        static_version: pub/ldv
        static_repo: https://git.interactions-team.fr/Koromix/rygel.git
        static_build:
          - '{{ static_root_path }}/repo/ldv-recherche.fr/www/web/ldv-recherche.fr/build.sh'
        static_path: bin/Web/ldv-recherche.fr
    - role: ../../roles/static
      vars:
        static_name: ldv-recherche.fr/beta
        static_repo: https://git.interactions-team.fr/Koromix/rygel.git
        static_build:
          - '{{ static_root_path }}/repo/ldv-recherche.fr/beta/web/ldv-recherche.fr/build.sh'
        static_path: bin/Web/ldv-recherche.fr
  tags: [ldv-recherche.fr, static]

- name: interactions-team.fr
  hosts: static
  roles:
    - role: ../../roles/static
      vars:
        static_name: interactions-team.fr/www
        static_repo: https://git.interactions-team.fr/Koromix/rygel.git
        static_path: web/interactions-team.fr
  tags: [interactions-team.fr, static]
