# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

discourse_repo: https://github.com/discourse/discourse_docker
discourse_commit: main

discourse_root_path: /opt/discourse

discourse_locale: en_US.UTF-8

# discourse_name:
# discourse_domain:
# discourse_admin:
# discourse_database:

# discourse_smtp:
