# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

forgejo_url: https://codeberg.org/forgejo/forgejo/releases/download/v10.0.2/forgejo-10.0.2-linux-amd64
forgejo_checksum: 'sha256:83b9fc2b1610d78d56251fefff892c30f9888a2a6cb6a8e39839b7768fa275a0'

forgejo_root_path: /opt/forgejo

forgejo_port: 3000
forgejo_config:

# forgejo_domain:
# forgejo_smtp:
