# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

forgejo_url: https://codeberg.org/forgejo/forgejo/releases/download/v13.0.0/forgejo-13.0.0-linux-amd64
forgejo_checksum: 'sha256:5fe0772da1dddf473d7b3da3a954554835dd5e845b56b6a90c34a6dad2db6df7'

forgejo_root_path: /opt/forgejo

forgejo_port: 3000
forgejo_config:

# forgejo_domain:
# forgejo_smtp:
