# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

forgejo_url: https://codeberg.org/forgejo/forgejo/releases/download/v12.0.0/forgejo-12.0.0-linux-amd64
forgejo_checksum: 'sha256:fd801557b17b68fd18b56a3102cbf27df4caac023a015e33d311694c51fea30d'

forgejo_root_path: /opt/forgejo

forgejo_port: 3000
forgejo_config:

# forgejo_domain:
# forgejo_smtp:
