# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

all:
  hosts:
    pri_cloud:
    pri_cpad:
    pri_forum:
    pri_tools:
    pri_watch:
    pub_cloud:
    pub_leaks:
    pub_web:
    vpn:

  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    public_domain: mla.local
    private_domain: intra.mla.local
    restrict_ssh_access: no
    force_self_ssl: yes
    private_gateway_ip: '{{ ansible_host }}'
