# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

# ------------------------------------------------------------------------
# Prometheus
# ------------------------------------------------------------------------

prometheus_root_path: /opt/prometheus # Installation directory

blackbox_scrape_interval: 2m
blackbox_scrape_timeout: 10s

# Define these to export Prometheus
# prometheus_exporters:

# Define these for blackbox probes
# blackbox_sites:

# ------------------------------------------------------------------------
# Grafana
# ------------------------------------------------------------------------

grafana_root_path: /opt/grafana

grafana_default_user: admin
grafana_default_password: grafana!16/default_pwd

# Set this to public Grafana URL to enable grafana
# grafana_url:
grafana_port: 9200

# Directory of provisioned Grafana dashboards and alerts
# grafana_dashboards: '{{ inventory_dir }}/prometheus/dashboards'
# grafana_alerts: '{{ inventory_dir }}/prometheus/alerting'
