# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

rekord_root_path: /opt/rekord

rekord_url: 'https://github.com/Koromix/rekord/releases/download/rekord%2F0.2/rekord_0.2_amd64.deb'
rekord_checksum: 'sha256:02bf7a59f2d54103cfad9792c21acab4b0ce83ccf92fd681660c0943d88e7a1e'

rekord_schedule: '*-*-* 5:00'
rekord_randomize: 20m

# rekord_environment:
# rekord_directories:
