# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

rekord_root_path: /opt/rekord

rekord_url: 'https://github.com/Koromix/rekord/releases/download/rekord%2F0.4/rekord_0.4_amd64.deb'
rekord_checksum: 'sha256:301a9519d0d7a707e2d1f15e44e1042800af97eb912f1c731ec4e9f202bbe0e7'

rekord_schedule: '*-*-* 5:00'
rekord_randomize: 20m

# rekord_environment:
# rekord_directories:
